# =====================================================
# * Copyright © hk. 2022-2025. All rights reserved.
# * File name  : _config.next.yml
# * Author     : 苏木
# * Date       : 2025-06-08
# * Version    : 0.0.1
# * Description: hexo-site/_config.yml中的 theme_config > "hexo-site/_config.[theme].yml" > "hexo-site/themes/theme-name/_config.yml"
# ======================================================
## https://hexo.io/zh-cn/docs/configuration

#################################################################
###################### NexT Configuration #######################
#################################################################

# ============================================================= #
# ======================  styles config ======================= #
# ============================================================= #
styles:
  header:
    enable: true
    background: /site-hexo/images/site-brand-bg.jpg


# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
  footer: source/_data/layout/footer.njk
  postBodyEnd: source/_data/layout/post-body-end.njk
  friendLinks: source/_data/layout/friend-links.njk

  style: source/_data/css/styles.styl


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini

darkmode: true

# ============================================================= #
# ================ Site Information Settings ================== #
# ============================================================= #
favicon:
  small: /images/favicon-16x16.ico
  medium: /images/favicon-32x32.ico
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
  #android_manifest: /manifest.json


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #
menu:
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  flink: /flink/ || fa fa-link
  about: /about/ || fa fa-user
  Theme Docs:
    default: /theme-next-docs/docs/ || fa fa-book

    Getting Started:
      default: /getting-started/ || fa fa-flag
      Installation: /installation.html || fa fa-download
      Deployment: /deployment.html || fa fa-upload
      Configuration: /configuration.html || fa fa-wrench
      Upgrade: /upgrade.html || fa fa-history

    Theme Settings:
      default: /theme-settings/ || fa fa-star
      Sidebar: /sidebar.html || fa fa-bars
      Footer: /footer.html || fa fa-sticky-note
      Posts: /posts.html || fa fa-paragraph
      Custom Pages: /custom-pages.html || fa fa-swatchbook
      Miscellaneous: /miscellaneous.html || fa fa-university
      SEO: /seo.html || fa fa-external-link-square-alt
      i18n: /internationalization.html || fa fa-language

    Tag Plugins:
      default: /tag-plugins/ || fa fa-rocket
      Button: /button.html || fa fa-cube
      Caniuse: /caniuse.html || fa fa-signal
      Group Pictures: /group-pictures.html || fa fa-images
      Label: /label.html || fa fa-hat-wizard
      Link Grid: /link-grid.html || fa fa-grip-vertical
      Mermaid: /mermaid.html || fa fa-project-diagram
      WaveDrom: /wavedrom.html || fa fa-diagram-predecessor
      Note: /note.html || fa fa-adjust
      PDF: /pdf.html || fa fa-file-pdf
      Tabs: /tabs.html || fa fa-columns

    Third Party Plugins:
      default: /third-party-services/ || fa fa-puzzle-piece
      Math Equations: /math-equations.html || fa fa-square-root-alt
      External Libraries: /external-libraries.html || fa fa-lightbulb
      Comment Systems: /comments.html || fa fa-comment-alt
      Post Widgets: /post-widgets.html || fa fa-gift
      Statistics and Analytics: /statistics-and-analytics.html || fa fa-chart-pie
      Search Services: /search-services.html || fab fa-algolia
      Chat Services: /chat-services.html || fa fa-comments

    Advanced Settings:
      default: /advanced-settings/ || fa fa-cog
      Vendors: /vendors.html || fa fa-plug
      Custom Files: /custom-files.html || fa fa-palette
      Injects: injects.html || fa fa-layer-group
      Front Matter: /front-matter.html || fa fa-edit

    Troubleshooting: /troubleshooting.html || fa fa-life-ring
  Plugins Docs:
    default: /plugins-docs/ || fa fa-book
    Tag Plugins:
      default: /TagsEmbed.html || fa fa-rocket

menu_settings:
  icons: true
  badges: true


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #
sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

avatar:
  url: /images/avatar.jpg
  rounded: true
  rotated: false

social:
  GitHub: https://github.com/sumumm || fab fa-github

social_icons:
  enable: true
  icons_only: false
  transition: true

toc:
  enable: true
  number: false
  wrap: false
  expand_all: false
  max_depth: 6


# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2025
  icon:
    name: fa fa-heart
    animated: true
    color: "#ff0000"
  copyright: 苏木
  powered: false
  sitetime:                 # 站点运行时间
    enable: true            # 是否开启站点运行时间
    text: 已在这里           # 最终输出为 已在这里 n 年 n 月 n 天 n 时 n 分 n 秒
    year: 2017              # 开始计时时间
    month: 5
    day: 19
    hour: 0
    minute: 0
    second: 0

# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #
## 文章添加结束标记
post_end_flag:
  enable: true              # 是否开启文章结束标记
  icon: fas fa-fan fa-spin  # 结束标记中的图标
  icon_color: '#FF1493'     # 图标颜色
  icon_size: 1rem           # 图标的大小

## 自定义版权信息
mine_creative:
  enable: true              # 自定义文章版权信息
  author: 苏木               # 文章作者
  blog_name: 《苏木》        # 博客名称
  license_link: https://creativecommons.org/licenses/by-nc-nd/4.0/ # 许可协议地址
  license_name: 署名-非商业性使用-禁止演绎 4.0 国际                     # 许可协议地址
  license_title: Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)   # 鼠标悬停显示内容

# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #
mobile_layout_economy: true

codeblock:
  theme:
    light: atom-one-light
    dark: atom-one-light
  copy_button:
    enable: true
    style: mac
  fold:
    enable: true
    height: 300

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

reading_progress:
  enable: true
  start_at: left
  position: bottom
  reversed: false
  color: "#DA70D6" # "#37c6c0" 进度条的颜色,#DA70D6为兰花的紫色 
  height: 6px

pace:
  enable: true
  color: green
  theme: minimal

# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true

mermaid:
  enable: true

wavedrom:
  enable: true

# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

local_search:
  enable: true
  top_n_per_article: 1

# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #
pjax: true

fancybox: true

lazyload: true

motion:
  async: true

# ============================================================= #
# ======================== custom pages ======================= #
# ============================================================= #

##友链样式 配置
flink_style: flexcard                       # next | flexcard


# ============================================================= #
# ===================== Comments Settings ===================== #
# ============================================================= #

giscus:
  enable: true
  repo: docs-site/site-hexo # Github repository name
  repo_id: R_kgDOO3rqzA # Github repository id
  category: General # Github discussion category
  category_id: DIC_kwDOO3rqzM4CuFwQ # Github discussion category id
  # Available values: pathname | url | title | og:title
  mapping: pathname
  # Available values: 0 | 1
  reactions_enabled: 1
   # Available values: 0 | 1
  emit_metadata: 1
  # Available values: light | light_high_contrast | light_protanopia | light_tritanopia | dark | dark_high_contrast | dark_protanopia | dark_tritanopia | dark_dimmed | preferred_color_scheme | transparent_dark | noborder_light | noborder_dark | noborder_gray | cobalt | purple_dark
  theme: light
  # Available values: en | zh-CN
  lang: zh-CN
  # Place the comment box above the comments
  input_position: top
  # Load the comments lazily
  loading: lazy

# ============================================================= #
# ======================== custom plugins ===================== #
# ============================================================= #

# 鼠标点击显示文字效果
ClickShowText:
  text:
    - 富强
    - 民主
    - 文明
    - 和谐
    - 自由
    - 平等
    - 公正
    - 法制
    - 爱国
    - 敬业
    - 诚信
    - 友善
  fontSize: 15px
  random: false
  mobile: false

TagsEmbed:
  enable: true   # 插件开关
  priority: 5    # 过滤器优先级
  CDN:
    tags_embed: https://cdn.jsdelivr.net/gh/docs-site/hexo-tags-embed@latest/lib/tag_embed.css
