# =====================================================
# * Copyright © hk. 2022-2025. All rights reserved.
# * File name  : _config.next.yml
# * Author     : 苏木
# * Date       : 2025-06-08
# * Version    : 0.0.1
# * Description: hexo-site/_config.yml中的 theme_config > "hexo-site/_config.[theme].yml" > "hexo-site/themes/theme-name/_config.yml"
# ======================================================
## https://hexo.io/zh-cn/docs/configuration

#################################################################
###################### NexT Configuration #######################
#################################################################


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini

darkmode: true

# ============================================================= #
# ================ Site Information Settings ================== #
# ============================================================= #
favicon:
  small: /images/favicon-16x16.ico
  medium: /images/favicon-32x32.ico
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
  #android_manifest: /manifest.json


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #
menu:
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  about: /about/ || fa fa-user
  Docs:
    default: /theme-next-docs/docs/ || fa fa-book

    Getting Started:
      default: /getting-started/ || fa fa-flag
      Installation: /installation.html || fa fa-download
      Deployment: /deployment.html || fa fa-upload
      Configuration: /configuration.html || fa fa-wrench
      Upgrade: /upgrade.html || fa fa-history

    Theme Settings:
      default: /theme-settings/ || fa fa-star
      Sidebar: /sidebar.html || fa fa-bars
      Footer: /footer.html || fa fa-sticky-note
      Posts: /posts.html || fa fa-paragraph
      Custom Pages: /custom-pages.html || fa fa-swatchbook
      Miscellaneous: /miscellaneous.html || fa fa-university
      SEO: /seo.html || fa fa-external-link-square-alt
      i18n: /internationalization.html || fa fa-language

    Tag Plugins:
      default: /tag-plugins/ || fa fa-rocket
      Button: /button.html || fa fa-cube
      Caniuse: /caniuse.html || fa fa-signal
      Group Pictures: /group-pictures.html || fa fa-images
      Label: /label.html || fa fa-hat-wizard
      Link Grid: /link-grid.html || fa fa-grip-vertical
      Mermaid: /mermaid.html || fa fa-project-diagram
      WaveDrom: /wavedrom.html || fa fa-diagram-predecessor
      Note: /note.html || fa fa-adjust
      PDF: /pdf.html || fa fa-file-pdf
      Tabs: /tabs.html || fa fa-columns

    Third Party Plugins:
      default: /third-party-services/ || fa fa-puzzle-piece
      Math Equations: /math-equations.html || fa fa-square-root-alt
      External Libraries: /external-libraries.html || fa fa-lightbulb
      Comment Systems: /comments.html || fa fa-comment-alt
      Post Widgets: /post-widgets.html || fa fa-gift
      Statistics and Analytics: /statistics-and-analytics.html || fa fa-chart-pie
      Search Services: /search-services.html || fab fa-algolia
      Chat Services: /chat-services.html || fa fa-comments

    Advanced Settings:
      default: /advanced-settings/ || fa fa-cog
      Vendors: /vendors.html || fa fa-plug
      Custom Files: /custom-files.html || fa fa-palette
      Injects: injects.html || fa fa-layer-group
      Front Matter: /front-matter.html || fa fa-edit

    Troubleshooting: /troubleshooting.html || fa fa-life-ring

menu_settings:
  icons: true
  badges: true


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #
sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

avatar:
  url: /images/avatar.jpg
  rounded: true
  rotated: false

social:
  GitHub: https://github.com/sumumm || fab fa-github

social_icons:
  enable: true
  icons_only: false
  transition: true

toc:
  enable: true
  number: false
  wrap: false
  expand_all: false
  max_depth: 6

# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #
mobile_layout_economy: true

codeblock:
  theme:
    light: atom-one-light
    dark: atom-one-light
  copy_button:
    enable: true
    style: mac
  fold:
    enable: true
    height: 300

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

reading_progress:
  enable: true
  start_at: left
  position: bottom
  reversed: false
  color: "#DA70D6" # "#37c6c0" 进度条的颜色,#DA70D6为兰花的紫色 
  height: 6px

pace:
  enable: true
  color: green
  theme: minimal

# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true

mermaid:
  enable: true

wavedrom:
  enable: true

# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

local_search:
  enable: true
  top_n_per_article: 1

